# Generated by Django 4.2.23 on 2025-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='stream',
            field=models.ManyToManyField(blank=True, related_name='videos', to='Course.stream'),
        ),
    ]
